#!/bin/sh

[ -c /dev/fb0 ] || exit 0

[ -f /etc/splash.ppm ] || exit 0

case "$1" in
     start)
	# Show splash screen
	fbset 640x480-60-rgba5551
	fbsplash -s /etc/splash.ppm
	;;
     stop)
	# Shut down screen?
	;;
esac
