#!/bin/sh
#
# /etc/init.d/udhcpc
#
case "$1" in
    start)
	if [ -e /sbin/udhcpc ]; then
	    ip link set eth0 up
	    /sbin/udhcpc -i eth0 -s /etc/udhcp/simple.script
	else
	    echo "No DHCP client found"
	fi

        ;;
    stop)
	killall -USR2 udhcpc
	;;
esac
